image:
  tag: 710effddb22f

resources:
  limits:
   cpu: 50m
   memory: 128Mi
  requests:
   cpu: 10m
   memory: 128Mi


## current b/c rate limit from letsencrypt:
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: frontend-sharecrows
  hosts:
    - my.sharecro.ws
    - sharecro.ws
    # - sharecrows.com
    # - my.sharecrows.com
  tls:
    - hosts:
        - sharecro.ws
        - my.sharecro.ws
      secretName: sharecrows-frontend-tls-stage
